language: java
jdk:
  - oraclejdk11
env:
  logsdir=/non-existing-directory
before_install:
  - whoami
  - sudo mkdir /var/log/webprotege && sudo chown travis /var/log/webprotege
script: mvn verify
sudo: false
services: mongodb
